// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCdOGrRR4i4x38Ze5QwF5JqS5wBjfL48M',
    appId: '1:1076478956998:web:f2e5d7374ad37657af8ec7',
    messagingSenderId: '1076478956998',
    projectId: 'poc-remote-config-92983',
    authDomain: 'poc-remote-config-92983.firebaseapp.com',
    storageBucket: 'poc-remote-config-92983.appspot.com',
    measurementId: 'G-4EXNY87GWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkuls7YHbzHrw5Cqo04ztxNX7FRsVgvqQ',
    appId: '1:1076478956998:android:324235ff62ee434daf8ec7',
    messagingSenderId: '1076478956998',
    projectId: 'poc-remote-config-92983',
    storageBucket: 'poc-remote-config-92983.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9RxLQ4Yw805cZW3esY17UJ0gSAn8XU4w',
    appId: '1:1076478956998:ios:65039916fa9edb8eaf8ec7',
    messagingSenderId: '1076478956998',
    projectId: 'poc-remote-config-92983',
    storageBucket: 'poc-remote-config-92983.appspot.com',
    iosClientId: '1076478956998-s6vfeq35ccnsoinq4qjhk43bhovrq0rj.apps.googleusercontent.com',
    iosBundleId: 'pocremoteconfig',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9RxLQ4Yw805cZW3esY17UJ0gSAn8XU4w',
    appId: '1:1076478956998:ios:c7eadbabe856fcafaf8ec7',
    messagingSenderId: '1076478956998',
    projectId: 'poc-remote-config-92983',
    storageBucket: 'poc-remote-config-92983.appspot.com',
    iosClientId: '1076478956998-p471245g152rdnitr4fnaskmenn6hq2p.apps.googleusercontent.com',
    iosBundleId: 'com.example.pocRemoteConfig',
  );
}
